language: generic
sudo: required  # We need full permission
services:
    - docker

before_install:
    - docker build -t radonjap/docker-react -f Dockerfile.dev . #build image

script:
    - docker run -e CI=true radonjap/docker-react npm run test -- --coverage
    # --coverage is added to automatically exit after-test menu

deploy:  # Deploying to AWS
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-197470864113"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY